import { UserRole, User, QDF, QDFStatus, Notification, ActivityLog, Qualification, QDF2Decision, QAChecklistData, QAChecklistStatus } from './types';

export const USERS: User[] = [
  { id: 'u1', name: 'Admin User', email: 'admin@navttc.gov.pk', role: UserRole.NAVTTCA_ADMIN, avatar: 'https://picsum.photos/seed/u1/40/40' },
  { id: 'u2', name: 'TEVTA Rep', email: 'tevta@example.com', role: UserRole.TEVTA_REP, avatar: 'https://picsum.photos/seed/u2/40/40' },
  { id: 'u3', name: 'QDC Member', email: 'qdc@example.com', role: UserRole.QDC_MEMBER, avatar: 'https://picsum.photos/seed/u3/40/40' },
  { id: 'u4', name: 'Industry Expert', email: 'expert@industry.com', role: UserRole.INDUSTRY_EXPERT, avatar: 'https://picsum.photos/seed/u4/40/40' },
  { id: 'u5', name: 'Training Provider', email: 'provider@training.com', role: UserRole.TRAINING_PROVIDER, avatar: 'https://picsum.photos/seed/u5/40/40' },
  { id: 'u6', name: 'System Admin', email: 'sysadmin@qds.com', role: UserRole.SYSTEM_ADMIN, avatar: 'https://picsum.photos/seed/u6/40/40' },
];

export const QA_CHECKLIST_ITEMS: string[] = [
    'Qualification title reflects the scope of the qualification and occupational area at the specified NVQF Level.',
    'Rationale for the qualification is provided.',
    'The competency units have been selected from the competency standards or developed with the involvement of industry experts to meet the qualification requirements.',
    'The structure of the qualification is as per NVQF requirements (core/elective units).',
    'Qualification development process is as per NAVTTC manual.',
    'The qualification leads to employment.',
    'The qualification is endorsed by the relevant industry sector.',
];


const approvedChecklist: QAChecklistData = {
    items: {
        0: 'Yes', 1: 'Yes', 2: 'Yes', 3: 'Yes', 4: 'Yes', 5: 'Yes', 6: 'Yes'
    },
    comments: 'All documents are in order and industry endorsement is confirmed. Approved for publication.',
    assessedBy: 'Director General NAVTTC',
    assessedByDesignation: 'Director General',
    assessedBySignature: 'DG NAVTTC',
    assessmentDate: '2023-11-20',
};


export let QDF_DATA: QDF[] = [
  { 
    id: 'QDF001', 
    title: 'Professional Cloud Developer', 
    level: 5, 
    sector: 'Information Technology', 
    status: QDFStatus.APPROVED, 
    submittedBy: 'TEVTA Punjab', 
    submissionDate: '2023-10-15', 
    lastUpdated: '2023-11-20',
    organizationName: 'Punjab TEVTA',
    organizationType: 'Provincial Authority',
    organizationAddress: '96-H Gulberg 2, Lahore',
    contactPersonName: 'Mr. Ali Khan',
    contactPersonDesignation: 'Director Q&A',
    contactPersonPhone: '0300-1234567',
    contactPersonEmail: 'ali.khan@tevta.gop.pk',
    description: 'A qualification focusing on modern cloud computing and DevOps practices.',
    justificationSummary: 'Covers key skills in AWS, Azure, GCP, and containerization.',
    justificationSupport: 'Supported by PSEB and P@SHA.',
    authorizedPerson: 'Chairman, TEVTA Punjab',
    dateReceived: '2023-10-15',
    dateReviewed: '2023-10-16',
    decision: QDF2Decision.APPROVED,
    submissionDueDate: '2024-01-15',
    reviewerSignature: 'Director General, NAVTTC',
    qdcMembers: [],
    qaChecklist: approvedChecklist,
    workflowHistory: [
        { stage: 'QDF-1 Submitted', user: 'TEVTA Rep', timestamp: '2023-10-15', status: 'completed' },
        { stage: 'NAVTTC Review', user: 'Admin User', timestamp: '2023-10-16', status: 'completed' },
        { stage: 'QDC Nomination', user: 'TEVTA Rep', timestamp: '2023-10-17', status: 'completed' },
        { stage: 'QDC Development', user: 'QDC Member', timestamp: '2023-11-01', status: 'completed' },
        { stage: 'CS Validation', user: 'Admin User', timestamp: '2023-11-05', status: 'completed' },
        { stage: 'Industry Validation', user: 'Industry Expert', timestamp: '2023-11-15', status: 'completed' },
        { stage: 'Final Approval', user: 'Admin User', timestamp: '2023-11-20', status: 'completed' },
        { stage: 'Published to Registry', user: 'System', timestamp: '2023-11-20', status: 'completed' },
    ]
  },
  { 
    id: 'QDF002', 
    title: 'Advanced Mechatronics Technician', 
    level: 6, 
    sector: 'Engineering', 
    status: QDFStatus.IN_DEVELOPMENT, 
    submittedBy: 'Sindh TEVTA', 
    submissionDate: '2023-11-01', 
    lastUpdated: '2023-11-22',
    organizationName: 'Sindh TEVTA',
    organizationType: 'Provincial Authority',
    organizationAddress: 'ST-19, Block 6, Gulshan-e-Iqbal, Karachi',
    contactPersonName: 'Ms. Fatima Jinnah',
    contactPersonDesignation: 'Deputy Director',
    contactPersonPhone: '0321-9876543',
    contactPersonEmail: 'fatima.jinnah@stevta.gos.pk',
    description: 'A qualification for high-tech industrial automation and robotics.',
    justificationSummary: 'Addresses the need for skilled technicians in modern manufacturing.',
    justificationSupport: 'Industry demand from major manufacturing companies.',
    authorizedPerson: 'Chairman, Sindh TEVTA',
    dateReceived: '2023-11-01',
    dateReviewed: '2023-11-02',
    decision: QDF2Decision.APPROVED,
    submissionDueDate: '2024-02-01',
    qdcMembers: [],
    qaChecklist: null,
    workflowHistory: [
        { stage: 'QDF-1 Submitted', user: 'TEVTA Rep', timestamp: '2023-11-01', status: 'completed' },
        { stage: 'NAVTTC Review', user: 'Admin User', timestamp: '2023-11-02', status: 'completed' },
        { stage: 'QDC Nomination', user: 'TEVTA Rep', timestamp: '2023-11-03', status: 'completed' },
        { stage: 'QDC Development', user: 'QDC Member', timestamp: '2023-11-22', status: 'in_progress' },
        { stage: 'CS Validation', user: 'Admin User', timestamp: '', status: 'pending' },
        { stage: 'Industry Validation', user: 'Industry Expert', timestamp: '', status: 'pending' },
        { stage: 'Final Approval', user: 'Admin User', timestamp: '', status: 'pending' },
    ]
  },
  { 
    id: 'QDF003', 
    title: 'Solar Panel Technician', 
    level: 4, 
    sector: 'Renewable Energy', 
    status: QDFStatus.PENDING_FINAL_APPROVAL, 
    submittedBy: 'KP TEVTA', 
    submissionDate: '2023-12-01', 
    lastUpdated: '2024-01-10',
    organizationName: 'KP TEVTA',
    organizationType: 'Provincial Authority',
    organizationAddress: '5-771, Old Bara Road, University Town, Peshawar',
    contactPersonName: 'Mr. Ahmed Wali',
    contactPersonDesignation: 'Manager',
    contactPersonPhone: '0333-1122334',
    contactPersonEmail: 'ahmed.wali@kptevta.gov.pk',
    description: 'Qualification for installation, maintenance, and repair of solar power systems.',
    justificationSummary: 'Growing demand for renewable energy solutions nationwide.',
    justificationSupport: 'Endorsed by major solar energy providers.',
    authorizedPerson: 'Chairman, KP TEVTA',
    dateReceived: '2023-12-01',
    dateReviewed: '2023-12-02',
    decision: QDF2Decision.APPROVED,
    submissionDueDate: '2024-03-01',
    qdcMembers: [],
    qaChecklist: null,
    workflowHistory: [
        { stage: 'QDF-1 Submitted', user: 'TEVTA Rep', timestamp: '2023-12-01', status: 'completed' },
        { stage: 'NAVTTC Review', user: 'Admin User', timestamp: '2023-12-02', status: 'completed' },
        { stage: 'QDC Nomination', user: 'TEVTA Rep', timestamp: '2023-12-03', status: 'completed' },
        { stage: 'QDC Development', user: 'QDC Member', timestamp: '2023-12-20', status: 'completed' },
        { stage: 'CS Validation', user: 'Admin User', timestamp: '2023-12-25', status: 'completed' },
        { stage: 'Industry Validation', user: 'Industry Expert', timestamp: '2024-01-05', status: 'completed' },
        { stage: 'Final Approval', user: 'Admin User', timestamp: '2024-01-10', status: 'in_progress' },
        { stage: 'Published to Registry', user: 'System', timestamp: '', status: 'pending' },
    ]
  },
   { 
    id: 'QDF004', 
    title: 'Digital Marketing Assistant', 
    level: 4, 
    sector: 'Information Technology', 
    status: QDFStatus.PENDING_QDC_NOMINATION, 
    submittedBy: 'Balochistan TEVTA', 
    submissionDate: '2024-01-20', 
    lastUpdated: '2024-01-25',
    organizationName: 'Balochistan TEVTA',
    organizationType: 'Provincial Authority',
    organizationAddress: ' Sariab Road, Quetta',
    contactPersonName: 'Mr. Sardar Khan',
    contactPersonDesignation: 'Coordinator',
    contactPersonPhone: '0345-5566778',
    contactPersonEmail: 'sardar.khan@btevta.gov.pk',
    description: 'Entry-level qualification for digital marketing roles.',
    justificationSummary: 'Focus on social media marketing, SEO basics, and content creation.',
    justificationSupport: 'Demand from local IT houses and startups.',
    authorizedPerson: 'Chairman, Balochistan TEVTA',
    dateReceived: '2024-01-20',
    dateReviewed: '2024-01-25',
    decision: QDF2Decision.APPROVED,
    submissionDueDate: '2024-04-20',
    qdcMembers: [],
    qaChecklist: null,
    workflowHistory: [
        { stage: 'QDF-1 Submitted', user: 'TEVTA Rep', timestamp: '2024-01-20', status: 'completed' },
        { stage: 'NAVTTC Review', user: 'Admin User', timestamp: '2024-01-25', status: 'completed' },
        { stage: 'QDC Nomination', user: 'TEVTA Rep', timestamp: '', status: 'in_progress' },
        { stage: 'QDC Development', user: 'QDC Member', timestamp: '', status: 'pending' },
        { stage: 'CS Validation', user: 'Admin User', timestamp: '', status: 'pending' },
        { stage: 'Industry Validation', user: 'Industry Expert', timestamp: '', status: 'pending' },
        { stage: 'Final Approval', user: 'Admin User', timestamp: '', status: 'pending' },
        { stage: 'Published to Registry', user: 'System', timestamp: '', status: 'pending' },
    ]
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', title: 'QDF002 Submitted', description: 'QDF for "Advanced Mechatronics Technician" has been submitted for review.', timestamp: '2023-11-22 10:00 AM', read: false },
  { id: 'n2', title: 'QDF001 Approved', description: 'Your QDF "Professional Cloud Developer" has been approved and published.', timestamp: '2023-11-20 03:45 PM', read: true },
  { id: 'n3', title: 'New Comment on QDF002', description: 'An industry expert has left feedback on the competency standards.', timestamp: '2023-11-21 09:12 AM', read: false },
];

export const ACTIVITY_LOGS: ActivityLog[] = [
  { id: 'a1', user: 'Admin User', action: 'Approved', details: 'QDF001 - Professional Cloud Developer', timestamp: '2023-11-20 03:45 PM' },
  { id: 'a2', user: 'TEVTA Rep', action: 'Submitted', details: 'QDF002 - Advanced Mechatronics Technician', timestamp: '2023-11-22 10:00 AM' },
  { id: 'a3', user: 'Industry Expert', action: 'Commented', details: 'QDF002 - Competency Standards', timestamp: '2023-11-21 09:12 AM' },
  { id: 'a4', user: 'QDC Member', action: 'Updated', details: 'QDF002 - Curriculum Draft', timestamp: '2023-11-20 05:00 PM' },
  { id: 'a5', user: 'Admin User', action: 'Created User', details: 'John Doe - Industry Expert', timestamp: '2023-11-19 01:20 PM' },
];

export const QUALIFICATIONS_REGISTRY: Qualification[] = [
    { id: 'QR001', title: 'Professional Cloud Developer', sector: 'Information Technology', nvqfLevel: 5, approvalYear: 2023, version: '1.0' },
    { id: 'QR002', title: 'Certified Plumber', sector: 'Construction', nvqfLevel: 3, approvalYear: 2022, version: '2.1' },
    { id: 'QR003', title: 'Automotive Service Technician', sector: 'Automotive', nvqfLevel: 4, approvalYear: 2023, version: '1.2' },
    { id: 'QR004', title: 'Digital Marketing Specialist', sector: 'Information Technology', nvqfLevel: 5, approvalYear: 2021, version: '3.0' },
];